### PR TITLE
:arrow_up: Upgrade CPF validator dependency

### PR DESCRIPTION
**Pull request by LeoColman**
Upgrade CPF validator dependency

### CODE REVIEW

**Comment by renanrbs** [comment]
Hello there, the unit tests didn't compile, can u update there too?

**Comment by LeoColman** [comment]
I don't believe my changes are the ones that broke the unit tests

**Comment by renanrbs** [comment]
Closing due to inactivity

**Comment by LeoColman** [comment]
@renanrbs 
What am I supposed to do?
I didn't break the unit tests, they were already broken

**Comment by renanrbs** [comment]
When running from develop, the tests succeeded, but when the library is updated they fail

**Pull request closed without merging**
